syntax = "proto3";

package request;

import "struct.proto";

message Request {
  WsRequest ws_request = 1;
}

message WsRequest {
  string service_name = 1;
  string method = 2;
  bytes payload = 3;
  Metadata metadata = 4;
  int64 index = 5;
}


message MetadataComplexValues {
  fixed64 fixed64_value = 6;
}

message MetadataValues {
  string string_value = 1;
  MetadataComplexValues msg_value = 2;
}

message MetadataKeyValues {
  string key = 1;
  MetadataValues value = 2;
}

message Metadata {
  repeated MetadataKeyValues key_values = 1;
}


message KeepAliveRequest {
  KeepAlive payloads = 2;
}

message KeepAlive {
  uint32 value_should_2 = 1;
}


message SetOnline {
  uint32 is_online = 1;
  uint32 duration = 2;
}

message EditName {
  string name = 1;
}

message EditNickName {
  struct.StringValue nick_name = 1;
}

message EditAbout {
  struct.StringValue about = 1;
}

message CheckNickName {
  string nick_name = 1;
}

message EditSex {
  int32 sex = 1;
}

message EditBirthDate {
  int64 date = 1;
}

message EditAvatar {
  struct.FileLocation file_location = 1;
}

message RemoveAvatar {
  // The official Web codec uses this misspelling on the JSON-facing field.
  struct.Int64Value avater_id = 1;
}

message EditMyTimeZone {
  string tz = 1;
}

message EditMyPreferredLanguages {
  repeated string preferred_languages = 1;
}

message EditUserLocalName {
  int32 uid = 1;
  int64 access_hash = 2;
  string name = 3;
}

message SendMessage {
  struct.Peer peer = 1;
  int64 rid = 2;
  struct.Message message = 3;
  struct.InfoMessage reply_to = 5;
  struct.Peer ex_peer = 6;
}

message UpdateMessage {
  struct.Peer peer = 1;
  int64 rid = 2;
  struct.Message updated_message = 3;
}

message DeleteMessage {
  struct.Peer peer = 1;
  repeated int64 rids = 2;
  struct.DeleteDates dates = 3;
  struct.Int32Value just_mine = 4;
}

message ForwardMessages {
  struct.Peer peer = 1;
  repeated int64 rid = 2;
  repeated struct.HistoryMessageIdentifier forwarded_messages = 3;
}

message GetMessageViews {
  struct.Peer peer = 1;
  repeated struct.MessageId mids = 2;
  bool increment = 3;
}

message MessageSetReaction {
  struct.Peer peer = 1;
  int64 rid = 2;
  string code = 3;
  int64 date = 4;
}

message MessageRemoveReaction {
  struct.Peer peer = 1;
  int64 rid = 2;
  string code = 3;
  int64 date = 4;
}

message GetMessagesReactions {
  struct.Peer peer = 1;
  repeated struct.MessageId mids = 2;
  struct.Peer origin_peer = 3;
  repeated struct.MessageId origin_mids = 4;
}

message GetMessagesViews {
  struct.Peer peer = 1;
  repeated struct.MessageId mids = 2;
  bool increment = 3;
  repeated struct.MessageId correct_mids = 4;
}

message SendInlineCallback {
  struct.Peer peer = 1;
  struct.MessageId message_id = 2;
  struct.StringValue data = 3;
}

message GetWssUrl {
  int64 call_id = 1;
}

message StartGroupCall {
  struct.Peer peer = 1;
  int64 random_id = 2;
  bool video = 3;
  int32 mode = 4;
  repeated struct.Peer invitees = 5;
}

message JoinGroupCall {
  int64 call_id = 1;
  struct.StringValue name = 2;
}

message LeaveGroupCall {
  int64 call_id = 1;
  bool end = 2;
}

message InviteToCall {
  int64 call_id = 1;
  repeated struct.Peer invitees = 2;
}

message GetGroupCall {
  struct.Peer peer = 1;
}

message SendCallReaction {
  int64 call_id = 1;
  string reaction = 2;
}

message GetCallLogs {
  struct.Int64Value page_number = 1;
  struct.Int64Value page_size = 2;
  struct.Int64Value after_date = 3;
  struct.Int64Value before_date = 4;
}

message GetOngoingCalls {
  struct.Int64Value page_number = 1;
  struct.Int64Value page_size = 2;
}

message DeleteCallLogs {
  repeated struct.Int64Value call_ids = 1;
  bool all = 2;
  bool invert = 3;
}

message MuteParticipant {
  int64 call_id = 1;
  string identity = 2;
  string track_id = 3;
  bool revoke_publish_permission = 4;
}

message RemoveParticipant {
  int64 call_id = 1;
  string identity = 2;
  bool block_from_call = 3;
}

message StartRecording {
  int64 call_id = 1;
  string layout = 2;
  int32 quality = 3;
}

message StopRecording {
  int64 call_id = 1;
}

message UpdateCallLayout {
  int64 call_id = 1;
  string requested_layout = 2;
}

message GenerateCallLink {
  bool is_public = 1;
  struct.Int64Value call_id = 2;
  struct.StringValue title = 3;
}

message GetCallLinkDetails {
  string session = 1;
}

message AskToJoinCall {
  int64 call_id = 1;
  string name = 2;
}

message AnswerCallJoinRequest {
  int64 call_id = 1;
  string requester_identifier = 2;
  bool is_allowed = 3;
}

message SetCallLinkTitle {
  string title = 1;
  struct.Int64Value call_id = 2;
  struct.StringValue link_url = 3;
}

message GetCallState {
  int64 call_id = 1;
}

message AcceptCall {
  int64 call_id = 1;
  struct.BoolValue invite_enable = 2;
}

message DiscardCall {
  int64 call_id = 1;
  int32 duration = 2;
  int32 reason = 3;
  int32 type = 4;
}

message ReceiveCall { int64 call_id = 1; }

message StartCall {
  struct.Peer peer = 1;
  int64 rid = 2;
  bool video = 3;
  struct.InternalCall internal_call = 4;
  struct.SipCall sip_call = 5;
  struct.LiveKitCall live_kit_call = 6;
}

message DeleteStream { struct.ExPeer stream_user = 1; }

message StartStream {
  struct.ExPeer stream_user = 1;
  string url = 2;
  string rtmp_server = 3;
}

message SubmitCallFeedback {
  int64 call_id = 1;
  int32 rate = 2;
  struct.StringValue user_opinion = 3;
  int32 client = 4;
  struct.StringValue client_version = 5;
  map<string, bytes> extra_fields = 6;
  struct.BoolValue is_stream = 7;
}

message TakeCallAction {
  int64 call_id = 1;
  struct.LowerHand lower_hand = 2;
  struct.RaiseHand raise_hand = 3;
}

message GetMyGroups {
  int32 mode = 1;
  bool is_owner = 2;
  repeated struct.GroupFilter filters = 3;
}

message LoadGroups { repeated struct.GroupOutPeer peers = 1; }

message GetMemberPermissions {
  struct.GroupOutPeer group = 1;
  struct.UserOutPeer user = 2;
}

message GetCanSeeMessages {
  struct.GroupOutPeer group_peer = 1;
  int32 user_id = 2;
}

message FetchGroupAdmins { struct.GroupOutPeer group_out_peer = 1; }
message GetBannedUsers { struct.GroupOutPeer group = 1; }
message GetMutualGroups { struct.UserOutPeer peer = 1; }

message LoadHistory {
  struct.Peer peer = 1;
  int64 date = 2;
  int32 load_mode = 4;
  int32 limit = 5;
  repeated int32 optimizations = 6;
}

message ClearChat {
  struct.Peer peer = 1;
}

message DeleteChat {
  struct.Peer peer = 1;
}

message MessageRead {
  struct.Peer peer = 1;
  int64 date = 2;
}

message JoinGroup {
  string token = 1;
  repeated int32 optimizations = 2;
}

message JoinPublicGroup {
  struct.Peer peer = 1;
  repeated int32 optimizations = 2;
}

message LeaveGroup {
  struct.GroupOutPeer group_peer = 1;
  int64 rid = 2;
  repeated int32 optimizations = 3;
  bool make_orphan = 4;
}

message LoadUsers {
  repeated struct.UserOutPeer user_peers = 1;
}

message LoadFullUsers {
  repeated struct.UserOutPeer user_peers = 1;
}

message GetFullUser {
  struct.UserOutPeer peer = 1;
}

message LoadFullUsersSequentially {
  repeated struct.UserOutPeer user_peers = 1;
}

message LoadAvatars {
  struct.UserOutPeer peer = 1;
}

message BlockUser {
  struct.UserOutPeer peer = 1;
}

message UnblockUser {
  struct.UserOutPeer peer = 1;
}

message LoadBlockedUsers {
}

message GetContacts {
  string contacts_hash = 1;
  repeated int32 optimizations = 2;
}

message RemoveContact {
  int32 uid = 1;
  int64 access_hash = 2;
}

message AddContact {
  int32 uid = 1;
  int64 access_hash = 2;
}

message GetUserPrivacyStatus {
  int32 user_id = 1;
  int32 type = 2;
}

message SetUserPrivacyStatus {
  int32 user_id = 1;
  int32 type = 2;
  int32 status = 3;
}

message GetUserFullPrivacy {
  int32 user_id = 1;
}

message GetFullGroup {
  struct.GroupOutPeer peer = 1;
}

message GetGroupPreview {
  string token = 1;
}

message SearchContacts {
  string request = 1;
  repeated int32 optimizations = 2;
}

message CreateGroup {
  int64 random_id = 1;
  string title = 2;
  repeated struct.UserOutPeer users = 3;
  int32 group_type = 6;
  struct.StringValue username = 8;
  int32 restriction = 9;
}

// Pin Message (Group)
message PinMessage {
  int32 sender_user_id = 1;
  struct.GroupOutPeer group_peer = 2;
  int64 date = 3;
  int64 msg_rid = 4;
}

// Pin Messages (Messaging)
message PinMessages {
  struct.Peer peer = 1;
  struct.MessageId message_id = 2;
  bool just_mine = 3;
}

message UnPinMessages {
  struct.ExPeer peer = 1;
  repeated struct.MessageId message_ids = 2;
  bool all = 3;
}

message EditGroupAvatar {
  struct.GroupOutPeer group_peer = 1;
  struct.FileLocation file_location = 3;
  int64 rid = 4;
  repeated int32 optimizations = 5;
}

message LoadGroupAvatars {
  struct.GroupOutPeer peer = 1;
}

message RemoveGroupAvatar {
  struct.GroupOutPeer group_peer = 1;
  int64 rid = 4;
  repeated int32 optimizations = 5;
  struct.Int64Value avatar_id = 6;
}

message EditGroupTitle {
  struct.GroupOutPeer group_peer = 1;
  string title = 3;
  int64 rid = 4;
  repeated int32 optimizations = 5;
}

message EditGroupAbout {
  struct.GroupOutPeer group_peer = 1;
  int64 rid = 2;
  struct.StringValue about = 3;
  repeated int32 optimizations = 5;
}

message RevokeInviteUrl {
  struct.GroupOutPeer group_peer = 1;
}

message UnBanUser {
  struct.GroupOutPeer group_peer = 1;
  struct.UserOutPeer user = 2;
  repeated int32 optimizations = 3;
}

message KickUser {
  struct.GroupOutPeer group_peer = 1;
  struct.UserOutPeer user = 3;
  int64 rid = 4;
  repeated int32 optimizations = 5;
}

message GetGroupInviteUrl {
  struct.GroupOutPeer group_peer = 1;
}

message InviteUsers {
  struct.GroupOutPeer group_peer = 1;
  int64 rid = 2;
  repeated struct.UserOutPeer users = 3;
}

message SetMemberPermissions {
  struct.GroupOutPeer group = 1;
  struct.UserOutPeer user = 2;
  struct.Permissions permissions = 3;
}

message LoadMembers {
  struct.GroupOutPeer group = 1;
  int32 limit = 2;
  struct.StringValue next = 3;
  struct.LoadMembersCondition condition = 4;
}

message GetGroupMembersCount {
  struct.GroupOutPeer group = 1;
}

message GetNasimFileUploadUrl {
  int32 expected_size = 1;
  int64 crc = 2;
  int64 uid = 3;
  string name = 4;
  string mime_type = 5;
  struct.ExPeer ex_peer = 6;
  struct.SendTypeValue send_type = 7;
  int64 chunk_size = 8;
}

message GetUploadLimits {
}

message StartPhoneAuth {
  int64 phone_number = 1;
  int32 app_id = 2;
  string api_key = 3;
  string device_hash = 4;
  string device_title = 5;
  int32 send_code_type = 9;
  bytes options = 10;
}

message ValidateCode {
  string transaction_hash = 1;
  string code = 2;
  struct.BoolValue is_jwt = 3;
}

message ValidatePassword {
  string transaction_hash = 1;
  string password = 2;
  struct.BoolValue is_jwt = 3;
}

message SignUp {
  string transaction_hash = 1;
  string name = 2;
  int32 sex = 3;
  struct.StringValue password = 4;
}

message TerminateAllSessions {
}

message GetJWTToken {
}

message GetAuthSessions {
}

message TerminateSession {
  int32 uid = 1;
  struct.ExInfo ex_info = 2;
}

message SignOut {
}

message SendGiftPacketWithWallet {
  struct.Peer peer = 1;
  int64 random_id = 2;
  struct.GiftPacket gift = 3;
  string token = 4;
}

message OpenGiftPacket {
  struct.InfoMessage message = 1;
  string receiver_token = 2;
  bytes page_no = 3;
  int32 order_type = 4;
}

message UpvotePost {
  struct.InfoMessage message = 1;
  struct.Int64Value album_id = 2;
}

message GetMyKifpools {
}

message GetParameters {
}

message ReportInappropriateContent {
  struct.Report report_body = 1;
}

message LoadPinnedMessages {
  struct.ExPeer peer = 1;
}

message RemoveSinglePin {
  struct.GroupOutPeer group_peer = 1;
  int64 rid = 2;
  int64 date = 3;
}

message RemovePin {
  struct.GroupOutPeer group_peer = 1;
}

message Typing {
  struct.OutPeer peer = 1;
  struct.TypingType typing_type = 3;
}

message StopTyping {
  struct.Peer peer = 1;
  struct.TypingType typing_type = 2;
}

message RemoveUserAdmin {
  struct.GroupOutPeer group_peer = 1;
  struct.UserOutPeer user_peer = 2;
}

message GetNasimFileUrl {
  struct.FileLocation file = 1;
}

message GetNasimFileUrls {
  struct.OutPeer peer = 1;
  struct.FileLocation file = 2;
  struct.StringValue filename = 3;
}

message GetNasimFileUploadResume {
  struct.FileLocation file = 1;
}

message FileUploadCancel {
  struct.FileLocation file = 1;
}

message GetNasimFilePublicUrl {
  struct.OutPeer peer = 1;
  struct.FileLocation file = 2;
  struct.StringValue filename = 3;
}

message SendMultiMediaMessage {
  struct.ExPeer peer = 1;
  repeated struct.SingleMedia multi_media = 2;
  //struct.MessageOutReference replied_message = 3;
  uint64 grouped_id = 4;
}

message LoadDialogs {
  int64 min_date = 1;
  int32 limit = 2;
  repeated int32 optimizations = 3;
  int32 dialog_type = 4;
  bool exclude_pinned_dialogs = 5;
  int32 archive_filter = 6;
}

message EditParameter {
  string key = 1;
  struct.StringValue value = 2;
}
