syntax = "proto3";

package response;

import "struct.proto";

message Response {
  WsResponse ws_response = 1;
  WsUpdate ws_update = 2;
}

message WsResponse {
  WsError error = 1;
  bytes response = 2;
  int64 index = 3;
}

message WsError {
  int32 code = 1;
  string message = 2;
  struct.MapValue details = 3;
}

message WsUpdate {
  Update update = 1;
}

message Update {
  ComposedUpdate composed_update = 1;
}

message ComposedUpdate {
  MessageSent message_sent = 4;
  MessageRead message_read = 19;
  ThreadDeleteMessage message_delete = 46;
  MessageReadByMe message_read_by_me = 50;
  MessageReceived message_received = 54;
  UpdateMessage message = 55;
  EmptyUpdate empty_update = 85;
  ThreadEditMessage message_content_changed = 162;
  MessageDateChanged message_date_changed = 163;
  MessageQuotedChanged message_quoted_changed = 169;
  MessageReaction reactions_update = 222;
  CallStarted call_started = 52807;
  CallAccepted call_accepted = 52808;
  CallDiscarded call_discarded = 52809;
  CallReceived call_received = 52810;
  GroupCallStarted group_call_started = 52811;
  GroupCallEnded group_call_ended = 52812;
  CallReactionSent call_reaction_sent = 52813;
  CallLinkGenerated call_link_generated = 52826;
  CallJoinRequestReceived call_join_request_received = 52827;
  CallJoinRequestAnswered call_join_request_answered = 52828;
  MessageReaction message_reactions = 52825;
  MessageNewReaction message_new_reaction = 54323;
  CallEvent call_event = 54324;
}

message EmptyUpdate {}

message MessageSent {
  struct.Peer peer = 1;
  int64 rid = 2;
  int64 date = 3;
  struct.MessageId previous_message_id = 4;
}

message MessageRead {
  struct.Peer peer = 1;
  int64 start_date = 2;
  int64 read_date = 3;
}

message MessageReadByMe {
  struct.Peer peer = 1;
  int64 start_date = 2;
  struct.Int32Value unread_counter = 3;
  struct.Int64Value end_date = 4;
}

message MessageReceived {
  struct.Peer peer = 1;
  int64 start_date = 2;
  int64 received_date = 3;
}

message ThreadDeleteMessage {
  struct.Peer peer = 1;
  repeated int64 rids = 2;
  struct.DeleteDates dates = 3;
  repeated struct.MessageId thread_ids = 4;
  repeated struct.Int32Value quoted_comment_reply_sender_ids = 5;
}

message ThreadEditMessage {
  struct.Peer peer = 1;
  int64 rid = 2;
  struct.Message message = 3;
  struct.Int64Value date = 4;
  struct.Int32Value updater_user_id = 5;
  struct.MessageId thread_id = 6;
  struct.Int32Value quoted_comment_reply_sender_id = 7;
  struct.Message updated_content_type_message = 8;
  struct.ExPeer ex_peer = 9;
}

message MessageDateChanged {
  struct.Peer peer = 1;
  int64 rid = 2;
  int64 date = 3;
}

message MessageQuotedChanged {
  struct.Peer peer = 1;
  int64 rid = 2;
  struct.QuotedMessage quoted_message = 3;
}

message MessageReaction {
  struct.Peer peer = 1;
  int64 rid = 2;
  repeated struct.Reaction reactions = 3;
  int64 date = 4;
}

message MessageNewReaction {
  struct.ExPeer ex_peer = 1;
  struct.MessageId message_id = 2;
}

message CallStarted {
  struct.Call call = 1;
  repeated struct.Peer participants = 2;
}

message CallAccepted {
  struct.Call call = 1;
  repeated struct.Peer participants = 2;
}

message CallDiscarded {
  struct.Call call = 1;
  repeated struct.Peer participants = 2;
}

message CallReceived {
  int64 call_id = 1;
  repeated struct.Peer participants = 2;
}

message GroupCallStarted {
  struct.GroupCall group_call = 1;
  int32 seq = 2;
}

message GroupCallEnded {
  struct.GroupCall group_call = 1;
}

message CallReactionSent {
  struct.OutPeer sender = 1;
  struct.OutPeer peer = 2;
  string reaction = 3;
}

message CallLinkGenerated {
  struct.GroupCall group_call = 1;
}

message CallJoinRequestReceived {
  int64 call_id = 1;
  string requester_identifier = 2;
  string name = 3;
}

message CallJoinRequestAnswered {
  bool is_allowed = 1;
  int64 call_id = 2;
}

message CallEvent {
  int64 call_id = 1;
  string triggerer_identity = 2;
  int32 type = 3;
  map<string, bytes> extra_data = 4;
}


message UpdateMessage {
  struct.Peer peer = 1;
  int32 sender_uid = 2;
  int64 date = 3;
  int64 rid = 4;
  struct.Message message = 5;
  struct.QuotedMessage quoted_message = 7;
  struct.MessageId previous_message_id = 9;
}

message GetMessageViews {
  repeated struct.MessagesViews containers = 1;
}

message LoadHistory {
  repeated struct.MessageContainer history = 1;
}

message JoinGroup {
  struct.Group group = 1;
  int32 seq = 2;
}

message JoinPublicGroup {
  struct.Group group = 1;
  int32 seq = 2;
}

message LoadUsers {
  repeated struct.User users = 1;
}

message LoadFullUsers {
  repeated struct.FullUser full_users = 1;
}

message CheckNickName {
  bool value = 1;
}

message SequenceResponse {
  int32 seq = 1;
  bytes state = 2;
  int64 seq_big = 3;
}

message EmptyResponse {
}

message EditAvatar {
  struct.Avatar avatar = 1;
  int32 seq = 2;
  bytes state = 3;
}

message GetFullUser {
  struct.UserProfile full_user = 1;
}

message LoadAvatars {
  struct.Avatars avatars = 1;
}

message LoadBlockedUsers {
  repeated struct.UserOutPeer user_peers = 1;
}

message GetContacts {
  repeated struct.User users = 1;
  bool is_not_changed = 2;
  repeated struct.UserOutPeer user_peers = 3;
}

message GetUserPrivacyStatus {
  int32 status = 1;
}

message GetUserFullPrivacy {
  struct.FullPrivacy privacy = 1;
}

message GetFullGroup {
  struct.FullGroup full_group = 1;
}

message GetGroupPreview {
  struct.FullGroup group = 1;
  int32 action = 2;
}

message SearchContacts {
  repeated struct.User users = 1;
  repeated struct.UserOutPeer user_peers = 2;
  repeated struct.Group groups = 4;
  repeated struct.GroupOutPeer group_peers = 5;
}

message CreateGroup {
  int32 seq = 1;
  int64 date = 2;
  struct.Group group = 3;
  repeated struct.UserOutPeer users = 5;
  repeated struct.UserOutPeer not_added_users = 6;
  string invite_link = 7;
}

message EditGroupAvatar {
  struct.Avatar avatar = 1;
  int32 seq = 2;
  bytes state = 3;
  int64 date = 4;
}

message GetGroupInviteUrl {
  string url = 1;
}

message RevokeInviteUrl {
  string url = 1;
}

message InviteUsers {
  repeated struct.UserOutPeer not_added_user_peers = 1;
}

message LoadMembers {
  repeated struct.Member members = 1;
  bytes next = 2;
}

message GetGroupMembersCount {
  int32 members_count = 1;
}

message GetNasimFileUploadUrl {
  int64 file_id = 1;
  string url = 2;
  bool duplicate = 3;
  int32 chunk_size = 4;
  int64 block_size = 5;
}

message GetUploadLimits {
  int64 upload_limit_bytes = 1;
  int64 temporary_max_bytes = 2;
  int64 permanent_max_bytes = 3;
  int64 bought_capacity_remaining_bytes = 4;
  bool bought_capacity_unlimited = 5;
}

message StartPhoneAuth {
  string transaction_hash = 1;
  bool is_registered = 2;
  int32 sent_code_type = 5;
  struct.Int64Value code_expiration_date = 6;
  int32 next_send_code_type = 7;
  struct.Int64Value next_send_code_wait_time = 8;
  struct.Int32Value code_timeout = 9;
}

message Auth {
  struct.User user = 2;
  struct.StringValue jwt = 4;
}

message GetJWTToken {
  struct.StringValue jwt = 1;
}

message LoadGroupAvatars {
  struct.Avatars avatars = 1;
}

message LoadPinnedMessages {
  repeated struct.MessageContainer pinned_messages = 1;
}

message GetNasimFileUrl {
  struct.FileUrlDescription file_url = 1;
}

message GetNasimFileUrls {
  repeated struct.FileUrlDescription file_urls = 1;
}

message GetNasimFileUploadResume {
  struct.FileUrlDescription file_url = 1;
  bool can_resume = 2;
}

message FileUploadCancel {
  bool canceled = 1;
}

message GetNasimFilePublicUrl {
  struct.FileUrlDescription file_url = 1;
}

message AuthSession {
  int32 id = 1;
  int32 auth_holder = 2;
  int32 app_id = 3;
  string app_title = 4;
  string device_title = 5;
  int32 auth_time = 6;
  string auth_location = 7;
  struct.DoubleValue latitude = 8;
  struct.DoubleValue longitude = 9;
  struct.Int64Value last_activity_at = 10;
  struct.StringValue last_ip_address = 11;
}

message GetAuthSessions {
  repeated AuthSession sessions = 1;
}

message GetParameters {
  repeated struct.ExtKeyValue parameters = 1;
}

message LoadDialogs {
  repeated struct.Group groups = 1;
  repeated struct.User users = 2;
  repeated struct.Dialog dialogs = 3;
  repeated struct.UserOutPeer user_peers = 4;
  repeated struct.GroupOutPeer group_peers = 5;
}

message DefaultResponse {
  int32 seq = 1;
  int64 date = 2;
  bytes state = 3;
  map<string, struct.RawValue> ext = 4;
  int64 seq_big = 5;
}

message MessageSetReaction {
  repeated struct.Reaction reactions = 2;
}

message MessageRemoveReaction {
  repeated struct.Reaction reactions = 2;
}

message GetMessagesReactions {
  repeated struct.MessageReactionsContainer containers = 1;
}

message GetMessagesViews {
  repeated struct.MessageViewsContainer containers = 1;
}

message SendInlineCallback {
  bytes answer = 1;
}

message GetWssUrl {
  string url = 1;
}

message GroupCall {
  struct.GroupCall group_call = 1;
}

message GroupCallWithSequence {
  struct.GroupCall group_call = 1;
  int32 seq = 2;
}

message JoinGroupCall {
  struct.GroupCall group_call = 1;
  repeated struct.CallPeerState states = 2;
}

message InviteToCall {
  repeated struct.CallPeerState peer_states = 1;
}

message GenerateCallLink {
  struct.GroupCall group_call = 1;
  int64 link_expiration_period = 2;
}

message GetCallLogs {
  repeated struct.CallLog call_logs = 1;
  int32 total = 2;
}

message GetOngoingCalls {
  repeated struct.CallLog call_logs = 1;
}

message CallWithParticipants {
  struct.Call call = 1;
  repeated struct.Peer participants = 2;
  int32 seq = 3;
  struct.BoolValue is_stream = 5;
}

message StartStream { string stream_key = 1; }

message GetMyGroups { repeated struct.GroupOutPeer groups = 1; }
message LoadGroups { repeated struct.Group groups = 1; }
message GetMemberPermissions { struct.Permissions permissions = 1; }
message GetCanSeeMessages { bool can_see_messages = 1; }

message FetchGroupAdmins {
  repeated struct.UserOutPeer users = 1;
  repeated struct.Member admins = 2;
}

message GetBannedUsers { repeated struct.BannedUser banned_users = 3; }
message GetMutualGroups { repeated struct.GroupOutPeer groups = 1; }

enum GiftOpenning {
  GIFT_OPENNING_ALREADY_RECEIVED = 0;
  GIFT_OPENNING_SOLD_OUT = 1;
  GIFT_OPENNING_GIFT_CREATOR = 2;
  GIFT_OPENNING_SUCCESSFUL = 3;
  GIFT_OPENNING_PENDING = 4;
}

message OpenGiftPacket {
  repeated struct.Winner receivers = 1;
  GiftOpenning status = 2;
  int32 openned_count = 3;
  struct.Int64Value win_amount = 4;
  struct.Int64Value rank = 5;
}

message Upvote {
  repeated struct.InfoMessage messages = 1;
  int32 limit = 2;
}

message UpvoteResponse {
  Upvote upvote = 1;
}

message GetMyKifpools {
  repeated struct.Wallet wallet = 1;
  struct.StringValue first_name = 2;
  struct.StringValue last_name = 3;
}
