"""Generate protobuf classes and a registry for RPCs recovered from Bale Web."""

from __future__ import annotations

import json
import re
from pathlib import Path

from bale.methods import METHODS

ROOT = Path(__file__).resolve().parents[1]
AUDIT = ROOT / "protocol" / "official-web-5.5.1.json"
PROTO = ROOT / "src" / "bale" / "proto" / "recovered.proto"
REGISTRY = ROOT / "src" / "bale" / "recovered_methods.py"


def _safe_comment(value: str) -> str:
    return re.sub(r"[\r\n]+", " ", value)


def generate() -> None:
    audit = json.loads(AUDIT.read_text(encoding="utf-8"))
    selected = [
        method
        for method in audit["methods"]
        if (method["service"], method["method"]) not in METHODS
    ]

    stack = [
        codec
        for method in selected
        for codec in (method["request_codec"], method["response_codec"])
    ]
    codecs: set[str] = set()
    while stack:
        codec_id = stack.pop()
        if codec_id in codecs:
            continue
        codecs.add(codec_id)
        for field in audit["codecs"][codec_id]["fields"]:
            if field.get("reference"):
                stack.append(field["reference"])

    names = {
        codec: f"RecoveredMessage{index:04d}"
        for index, codec in enumerate(sorted(codecs), 1)
    }
    proto = [
        '// Generated by scripts/generate_recovered_protocol.py; do not edit.',
        'syntax = "proto3";',
        'package bale.recovered;',
        '',
    ]
    for codec_id in sorted(codecs):
        proto.append(f"// Web codec: {_safe_comment(codec_id)}")
        proto.append(f"message {names[codec_id]} {{")
        for field in audit["codecs"][codec_id]["fields"]:
            field_type = field["type"]
            if field_type == "message":
                field_type = names[field["reference"]]
            prefix = "repeated " if field["repeated"] else ""
            if field["map"]:
                entry = audit["codecs"][field["reference"]]["fields"]
                key_type = entry[0]["type"]
                value = entry[1]
                value_type = (
                    names[value["reference"]]
                    if value["type"] == "message"
                    else value["type"]
                )
                declaration = f"map<{key_type}, {value_type}>"
            else:
                declaration = f"{prefix}{field_type}"
            proto.append(
                f"  {declaration} {field['name']} = {field['number']};"
            )
        proto.extend(["}", ""])
    PROTO.write_text("\n".join(proto), encoding="utf-8")

    registry = [
        '"""Generated registry for RPCs recovered from the official Bale Web build."""',
        "",
        "from typing import Any",
        "",
        "from bale.proto import recovered_pb2 as _pb",
        "",
        "pb: Any = _pb",
        "",
        "RECOVERED_METHODS = {",
    ]
    for method in sorted(selected, key=lambda item: (item["service"], item["method"])):
        registry.extend(
            [
                "    (",
                f"        {method['service']!r},",
                f"        {method['method']!r},",
                "    ): (",
                f"        pb.{names[method['request_codec']]},",
                f"        pb.{names[method['response_codec']]},",
                "    ),",
            ]
        )
    registry.extend(["}", "", '__all__ = ["RECOVERED_METHODS"]', ""])
    REGISTRY.write_text("\n".join(registry), encoding="utf-8")


if __name__ == "__main__":
    generate()
